# Generated by Django 2.0 on 2020-10-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_coupon_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='percentage',
        ),
    ]
